// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bWEzaSdlPR-8-pF7Aw1PQuJF0UvLi88',
    appId: '1:333069425266:web:72033a14364d38f5f280eb',
    messagingSenderId: '333069425266',
    projectId: 'edufyauth',
    authDomain: 'edufyauth.firebaseapp.com',
    storageBucket: 'edufyauth.firebasestorage.app',
    measurementId: 'G-1334X3C0KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hXD42LgVjgm-Zp4uNYVtB5Wxaa3lYas',
    appId: '1:333069425266:android:2a0b82c6bcc6c8eff280eb',
    messagingSenderId: '333069425266',
    projectId: 'edufyauth',
    storageBucket: 'edufyauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAqqRikesFLiloeiCvFwdBH5SxdG_Il0Y',
    appId: '1:333069425266:ios:d1b73c4453fcf7c5f280eb',
    messagingSenderId: '333069425266',
    projectId: 'edufyauth',
    storageBucket: 'edufyauth.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAqqRikesFLiloeiCvFwdBH5SxdG_Il0Y',
    appId: '1:333069425266:ios:d1b73c4453fcf7c5f280eb',
    messagingSenderId: '333069425266',
    projectId: 'edufyauth',
    storageBucket: 'edufyauth.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3bWEzaSdlPR-8-pF7Aw1PQuJF0UvLi88',
    appId: '1:333069425266:web:95b510586bed2fccf280eb',
    messagingSenderId: '333069425266',
    projectId: 'edufyauth',
    authDomain: 'edufyauth.firebaseapp.com',
    storageBucket: 'edufyauth.firebasestorage.app',
    measurementId: 'G-TCN1N7QQB1',
  );

}